name: Build and deploy Three Stripes core to AKS
on:
  push:
    branches:
      - 'main'
      - 'dev'
  workflow_dispatch:

env:
  IMAGE_NAME: aks_poc_app
  CONTAINER_REGISTRY: ghcr.io/aks_poc_repo
  IMAGE_TAG: ${{ github.run_number }}
  CLUSTER_NAME: 
  RESOURCE_GROUP: 

jobs:
  build:
    name: Build & push docker image
    runs-on: ubuntu-latest
    env:
      IMG_NAME: ${{ github.repository }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ${{ env.CONTAINER_REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GH_TOKEN }}

      - name: Build Docker image
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: ${{ env.CONTAINER_REGISTRY }}/${{ env.IMAGE_NAME }}:${{ env.IMAGE_TAG }}
  
